title: Muhammad Adil
description: Lecturer, researcher, and AI/medical imaging professional.
url: "https://m-adilk.github.io"
baseurl: ""

collections:
  certificates:
    output: true
    permalink: /certificates/:name/
  galleries:
    output: true
    permalink: /gallery/:name/
  pages:
    output: true
    permalink: /pages/:name/
  highlights:
    output: true
    permalink: /highlights/:name/
  qualifications:
    output: true
    permalink: /qualifications/:name/
  research:
    output: true
    permalink: /research/:name/
  experiences:
    output: true
    permalink: /experience/:name/

defaults:
  - scope:
      path: ""
      type: certificates
    values:
      layout: certificate
  - scope:
      path: ""
      type: galleries
    values:
      layout: gallery
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: highlights
    values:
      layout: highlight
  - scope:
      path: ""
      type: qualifications
    values:
      layout: qualification
  - scope:
      path: ""
      type: research
    values:
      layout: publication
  - scope:
      path: ""
      type: experiences
    values:
      layout: experience

exclude:
  - README.md
